apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: autochess
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 8000
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - name: autochess
            image: Dockerfile